import React from "react";
import Footer3 from "../footer/Footer3";
import Header from "../header/HeaderDashboard";
import useBodyClass from "@/hooks/useBodyClass";
import Head from "next/head";

function Layout({ children }) {
  useBodyClass("home-dark2");
  return (
    <>
      <Head>
        <title>Arys solutions- Software Agency and creative IT solution</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/img/sm-logo.svg" />
      </Head>
      <Header />
      {children}
    </>
  );
}

export default Layout;
